const savedWorkspace=JSON.parse(localStorage.getItem('cleanly-workspace-v1')||'null')||{};
const jobs=savedWorkspace.jobs||[];
const attention=[['⏱','Extra time pending','Anna Wilson logged 35 min extra at John Smith','Review'],['◉','Location needs review','Check-out was 112m from job address','Review'],['✉','Job declined','Sophie Lee cannot attend Harbour Office','Reassign'],['$','Invoice overdue','INV-1048 · $860.00 was due 2 days ago','View']];
const clients=savedWorkspace.clients||[];
const clientRates=savedWorkspace.clientRates||[];
const team=savedWorkspace.team||[];
const invoices=savedWorkspace.invoices||[];
const avatar=(initials, i=0)=>`<span class="avatar a${i%4+1}">${initials}</span>`;
document.querySelector('#todayJobs').innerHTML=jobs.map((j,i)=>`<div class="job-row"><div class="job-time">${j[0]}</div><div><div class="job-name">${j[1]}</div><div class="job-detail">${j[2]} <span>· 2h</span></div></div><div class="job-person">${avatar(j[4],i)} ${j[3]} <span class="pill ${j[5]}">${j[6]}</span></div></div>`).join('');
document.querySelector('#attentionList').innerHTML=attention.map(a=>`<div class="attention"><div class="attention-icon">${a[0]}</div><div><strong>${a[1]}</strong><p>${a[2]}</p></div><button>${a[3]}</button></div>`).join('');
document.querySelector('#jobsTable').innerHTML=jobs.concat([['Tomorrow','Solace Dental','Commercial clean','David Chen','DC','confirmed','Confirmed']]).map((j,i)=>`<tr><td><div class="client-cell">${avatar(j[1].split(' ').map(x=>x[0]).join('').slice(0,2),i)}<div><strong>${j[1]}</strong><small>${j[2]}</small></div></div></td><td>${j[0]}<small>4 Sep 2026</small></td><td>${j[3]}</td><td>2h 00m</td><td><span class="pill ${j[5]}">${j[6]}</span></td><td>${j[5]==='waiting'?`<button class="send-button" data-client="${j[1]}" data-cleaner="${j[3]}">✈ Send Telegram</button>`:'•••'}</td></tr>`).join('');
document.querySelector('#clientsTable').innerHTML=clients.map((c,i)=>`<tr><td><div class="client-cell">${avatar(c[0],i)}<strong>${c[1]}</strong></div></td><td>${c[2]}</td><td class="client-rate">$${clientRates[i].toFixed(2)}<small>per hour</small></td><td>${c[3]}</td><td>${c[4]}</td><td><span class="pill confirmed">${c[5]}</span></td><td><button class="edit-button edit-client" data-index="${i}">Edit</button></td></tr>`).join('');
document.querySelector('#teamGrid').innerHTML=team.map((t,i)=>`<article class="team-card">${avatar(t[0],i)}<button class="edit-button card-edit edit-team" data-index="${i}">Edit</button><h3>${t[1]}</h3><p>${t[2]}</p><footer><span class="${t[3].startsWith('On')?'on-shift':''}">● ${t[3]}</span><span>${t[4]}</span></footer></article>`).join('');
document.querySelector('#invoicesTable').innerHTML=invoices.map(r=>`<tr><td><strong>${r[0]}</strong></td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td><strong>${r[4]}</strong></td><td><span class="pill ${r[5]}">${r[6]}</span></td></tr>`).join('');
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('[data-view]').forEach(n=>n.classList.toggle('active',n.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'});}
document.querySelectorAll('[data-view]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();showView(el.dataset.view)}));
const modal=document.querySelector('#modal'),telegramModal=document.querySelector('#telegramModal'),toast=document.querySelector('#toast');
function openTelegram(client='Harbour Office',cleaner='David Chen'){document.querySelector('#telegramMessage').innerHTML=`Client: ${client}<br/>📍 18 Hay Street, Subiaco<br/>📅 Thursday, 4 September<br/>🕘 03:00 PM<br/>⏱️ Duration: 2 hours`;document.querySelector('#telegramCleaner').textContent=cleaner;telegramModal.classList.add('open')}
function notify(cleaner){document.querySelector('#toastText').textContent=`${cleaner.split(' ')[0]} will be notified on Telegram.`;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3600)}
document.querySelectorAll('#newJob,#newJobSchedule').forEach(b=>b.addEventListener('click',()=>modal.classList.add('open')));document.querySelector('.close-modal').onclick=()=>modal.classList.remove('open');modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});document.querySelector('.job-modal').addEventListener('submit',e=>{e.preventDefault();modal.classList.remove('open');openTelegram('John Smith','Anna Wilson')});
document.querySelectorAll('.send-button').forEach(b=>b.addEventListener('click',()=>openTelegram(b.dataset.client,b.dataset.cleaner)));document.querySelector('.close-telegram').onclick=()=>telegramModal.classList.remove('open');telegramModal.addEventListener('click',e=>{if(e.target===telegramModal)telegramModal.classList.remove('open')});document.querySelector('.send-telegram').onclick=()=>{const cleaner=document.querySelector('#telegramCleaner').textContent;telegramModal.classList.remove('open');document.querySelectorAll('.send-button').forEach(b=>{b.textContent='✓ Sent';b.classList.add('sent-button');b.disabled=true});notify(cleaner)};
const editModal=document.querySelector('#editModal');let editTarget=null;
function openEditor(kind,index){editTarget={kind,index};const row=kind==='client'?clients[index]:team[index];const isClient=kind==='client';document.querySelector('#editEyebrow').textContent=isClient?'CLIENT PROFILE':'TEAM MEMBER';document.querySelector('#editTitle').textContent=isClient?'Edit client':'Edit cleaner';document.querySelector('#editName').value=row[1];document.querySelector('#editEmail').value=isClient?'contact@'+row[1].toLowerCase().replaceAll(' ','')+'.com':row[1].toLowerCase().replaceAll(' ','')+'@cleanly.com';document.querySelector('#editFieldOneLabel').firstChild.textContent=isClient?'Service':'Role';document.querySelector('#editFieldTwoLabel').firstChild.textContent=isClient?'Frequency':'Status';document.querySelector('#editFieldOne').innerHTML=isClient?'<option>Regular home clean</option><option>Office cleaning</option><option>Commercial clean</option>':'<option>Cleaner</option><option>Senior Cleaner</option><option>Team Leader</option>';document.querySelector('#editFieldTwo').innerHTML=isClient?'<option>Weekly</option><option>Fortnightly</option><option>2× weekly</option>':'<option>On shift</option><option>Off today</option><option>Unavailable</option>';document.querySelector('#editFieldOne').value=isClient?row[2]:row[2];document.querySelector('#editFieldTwo').value=isClient?row[3]:(row[3].startsWith('On')?'On shift':'Off today');editModal.classList.add('open')}
document.querySelectorAll('.edit-client').forEach(b=>b.addEventListener('click',()=>openEditor('client',+b.dataset.index)));document.querySelectorAll('.edit-team').forEach(b=>b.addEventListener('click',()=>openEditor('team',+b.dataset.index)));document.querySelector('.close-edit').onclick=()=>editModal.classList.remove('open');editModal.addEventListener('click',e=>{if(e.target===editModal)editModal.classList.remove('open')});document.querySelector('.edit-modal').addEventListener('submit',e=>{e.preventDefault();const name=document.querySelector('#editName').value;const one=document.querySelector('#editFieldOne').value;const two=document.querySelector('#editFieldTwo').value;if(editTarget.kind==='client'){const item=clients[editTarget.index];item[1]=name;item[2]=one;item[3]=two;document.querySelector(`#clientsTable .edit-client[data-index="${editTarget.index}"]`).closest('tr').children[0].querySelector('strong').textContent=name;const cells=document.querySelector(`#clientsTable .edit-client[data-index="${editTarget.index}"]`).closest('tr').children;cells[1].textContent=one;cells[3].textContent=two}else{const item=team[editTarget.index];item[1]=name;item[2]=one;item[3]=two==='On shift'?'On shift · Available':two;const card=document.querySelector(`.edit-team[data-index="${editTarget.index}"]`).closest('.team-card');card.querySelector('h3').textContent=name;card.querySelector('p').textContent=one;card.querySelector('footer span').textContent='● '+item[3]}editModal.classList.remove('open');document.querySelector('#toastText').textContent=`${name}'s profile was updated.`;toast.querySelector('strong').textContent='Changes saved';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3600)});
