const attendance={scheduledMinutes:120,checkIn:null,startedAt:null,checkOut:null,checkInPhoto:null,checkOutPhoto:null,location:null};
const customerLocation={lat:-31.9481,lon:115.8193,address:'25 Smith Street, Subiaco WA 6008'};
let mediaStream=null,currentMode='checkin',attendanceLocation=null,photoCaptured=false;
const attendanceOverlay=document.createElement('div');attendanceOverlay.className='modal-backdrop';attendanceOverlay.id='attendanceModal';document.body.append(attendanceOverlay);
function formatDuration(minutes){const h=Math.floor(minutes/60),m=minutes%60;return `${h}h ${m}m`}
function distanceMeters(a,b){const r=6371e3,toRad=value=>value*Math.PI/180;const dLat=toRad(b.lat-a.lat),dLon=toRad(b.lon-a.lon);const x=Math.sin(dLat/2)**2+Math.cos(toRad(a.lat))*Math.cos(toRad(b.lat))*Math.sin(dLon/2)**2;return 2*r*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function stopCamera(){if(mediaStream){mediaStream.getTracks().forEach(track=>track.stop());mediaStream=null}}
function cameraMarkup(mode){const title=mode==='checkin'?'Check in at job':'Check out from job';const action=mode==='checkin'?'Confirm check-in':'Confirm check-out';return `<section class="job-modal attendance-modal"><button class="close-attendance close-modal" type="button">×</button><p class="eyebrow">LIVE ATTENDANCE</p><h2>${title}</h2><p class="subtle">Take a live photo of the front of the property. Uploading a photo is not available.</p><div class="attendance-step"><div class="camera-stage" id="cameraStage"><div class="camera-placeholder"><span>◉</span>Start the camera to take a live photo.</div></div></div><div class="location-check" id="locationCheck"><span>⌖</span><div><b>Location not captured</b><small>We will compare your GPS with ${customerLocation.address}.</small></div></div><div class="attendance-actions"><button class="invoice-button" id="startCamera">Open live camera</button><button class="new-job" id="capturePhoto" disabled>Capture photo</button><button class="new-job" id="confirmAttendance" disabled>${action}</button></div></section>`}
async function openCamera(mode){currentMode=mode;attendanceLocation=null;photoCaptured=false;attendanceOverlay.innerHTML=cameraMarkup(mode);attendanceOverlay.classList.add('open');attendanceOverlay.querySelector('.close-attendance').onclick=()=>{stopCamera();attendanceOverlay.classList.remove('open')};attendanceOverlay.querySelector('#startCamera').onclick=startCamera;attendanceOverlay.querySelector('#capturePhoto').onclick=capturePhoto;attendanceOverlay.querySelector('#confirmAttendance').onclick=confirmAttendance}
async function startCamera(){const stage=document.querySelector('#cameraStage');try{mediaStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});stage.innerHTML='<span class="live-tag">● LIVE</span><video id="liveCamera" autoplay playsinline></video>';document.querySelector('#liveCamera').srcObject=mediaStream;document.querySelector('#capturePhoto').disabled=false;captureLocation()}catch(error){stage.innerHTML='<div class="camera-placeholder"><span>!</span>Camera access is required for attendance photos. Please allow camera access and try again.</div>'}}
function captureLocation(){const box=document.querySelector('#locationCheck');if(!navigator.geolocation){box.innerHTML='<span>!</span><div><b>Location unavailable</b><small>This device does not support geolocation.</small></div>';return}navigator.geolocation.getCurrentPosition(position=>{const point={lat:position.coords.latitude,lon:position.coords.longitude};const meters=Math.round(distanceMeters(customerLocation,point));attendanceLocation={...point,meters};box.className='location-check '+(meters<=100?'location-valid':'location-warning');box.innerHTML=`<span>${meters<=100?'✓':'!'}</span><div><b>${meters<=100?'Location verified':'Location requires review'}</b><small>${meters}m from the client address. Allowed distance: 100m.</small></div>`;updateConfirm()},()=>{box.innerHTML='<span>!</span><div><b>Location permission required</b><small>Please allow location access before confirming attendance.</small></div>'},{enableHighAccuracy:true,timeout:10000})}
function capturePhoto(){const video=document.querySelector('#liveCamera');if(!video)return;const canvas=document.createElement('canvas');canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext('2d').drawImage(video,0,0);document.querySelector('#cameraStage').innerHTML='<span class="live-tag">✓ CAPTURED LIVE</span>';document.querySelector('#cameraStage').append(canvas);if(currentMode==='checkin')attendance.checkInPhoto=canvas.toDataURL('image/jpeg',.8);else attendance.checkOutPhoto=canvas.toDataURL('image/jpeg',.8);photoCaptured=true;stopCamera();updateConfirm();document.querySelector('#capturePhoto').disabled=true}
function updateConfirm(){const button=document.querySelector('#confirmAttendance');if(button)button.disabled=!(photoCaptured&&attendanceLocation)}
function confirmAttendance(){if(!attendanceLocation||!photoCaptured)return;attendance.location=attendanceLocation;const now=new Date();if(currentMode==='checkin'){attendance.checkIn=now;setPortalAction('start');showAttendanceToast('Check-in recorded','Live photo and location have been saved.')}else{attendance.checkOut=now;finishWork()}attendanceOverlay.classList.remove('open');stopCamera()}
function setPortalAction(state){const button=document.querySelector('.checkin-button');if(!button)return;if(state==='start'){button.textContent='▶ Start work';button.className='checkin-button start-work';button.onclick=startWork}else if(state==='finish'){button.textContent='✓ Finish work';button.className='checkin-button finish-work';button.onclick=()=>openCamera('checkout');document.querySelector('.arrival-note').innerHTML='<span class="work-timer">● Work in progress</span>'}}
function startWork(){attendance.startedAt=new Date();setPortalAction('finish');showAttendanceToast('Work started','Your working time is now being recorded.')}
function finishWork(){const end=attendance.checkOut||new Date();const started=attendance.startedAt||attendance.checkIn||end;const actual=Math.max(0,Math.round((end-started)/60000));const extra=Math.max(0,actual-attendance.scheduledMinutes);setPortalFinished(actual,extra);if(extra>0)createApproval(extra);else showAttendanceToast('Work completed',`Recorded ${formatDuration(actual)}. The client will be billed for the agreed 2h.`)}
function setPortalFinished(actual,extra){const action=document.querySelector('.cleaner-job-action');action.innerHTML=`<span class="arrival-note">Completed · ${formatDuration(actual)}</span><span class="job-tag">${extra?`${formatDuration(extra)} extra pending`:'2h agreed time'}</span>`}
function createApproval(extra){const list=document.querySelector('.attention-list');const item=document.createElement('div');item.className='approval-item';item.innerHTML=`<div class="extra-icon">⏱</div><div><strong>Extra time approval required</strong><small>Anna Wilson · John Smith · ${formatDuration(extra)} over the agreed 2h</small></div><button class="invoice-button primary">Review</button>`;list.prepend(item);item.querySelector('button').onclick=()=>openApproval(extra);showAttendanceToast('Extra time sent to admin',`${formatDuration(extra)} is pending approval. It will not be invoiced yet.`)}
function openApproval(extra){const overlay=document.createElement('div');overlay.className='modal-backdrop open';overlay.innerHTML=`<section class="job-modal approval-modal"><button class="close-approval close-modal">×</button><p class="eyebrow">ADMIN APPROVAL</p><h2>Approve extra time?</h2><div class="approval-summary"><b>John Smith · Anna Wilson</b><br/>Agreed time: <b>2h 00m</b><br/>Additional time: <b>${formatDuration(extra)}</b><br/><br/>Only approved time will be added to the customer invoice.</div><div class="approval-options"><button class="new-job approved-extra" id="approveExtra">Approve ${formatDuration(extra)}</button><button class="new-job deny-extra" id="denyExtra">Decline extra time</button></div></section>`;document.body.append(overlay);const close=()=>overlay.remove();overlay.querySelector('.close-approval').onclick=close;overlay.querySelector('#approveExtra').onclick=()=>{setInvoiceHours(2+extra/60,extra);close();showAttendanceToast('Extra time approved',`The invoice will include 2h + ${formatDuration(extra)}.`)};overlay.querySelector('#denyExtra').onclick=()=>{setInvoiceHours(2,0);close();showAttendanceToast('Extra time declined','The invoice will include only the agreed 2h.')};}
function setInvoiceHours(hours,extra){const johnInvoice=invoiceDetails.find(item=>item.customer==='John Smith');if(johnInvoice){johnInvoice.quantity=hours;johnInvoice.description=extra?`Regular cleaning · 2h agreed + ${formatDuration(extra)} approved`:'Regular cleaning · 2h agreed';}document.querySelectorAll('.approval-item').forEach(item=>item.remove())}
function showAttendanceToast(title,message){toast.querySelector('strong').textContent=title;document.querySelector('#toastText').textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),4400)}
document.querySelectorAll('.checkin-button').forEach(oldButton=>{const button=oldButton.cloneNode(true);oldButton.replaceWith(button);button.addEventListener('click',()=>openCamera('checkin'))});
