const clientLocationData=[
  {rate:55,gst:10,address:'25 Smith Street, Subiaco WA 6008, Australia',lat:-31.9481,lon:115.8193},
  {rate:68,gst:10,address:'44 Hay Street, Subiaco WA 6008, Australia',lat:-31.9509,lon:115.8141},
  {rate:75,gst:10,address:'18 Hay Street, Subiaco WA 6008, Australia',lat:-31.9514,lon:115.8135},
  {rate:58,gst:10,address:'7 Rokeby Road, Subiaco WA 6008, Australia',lat:-31.9487,lon:115.8174}
];
let addressTimer,selectedLocation=null;
const addressInput=document.querySelector('#clientAddress'),results=document.querySelector('#addressResults'),coordinates=document.querySelector('#coordinates');
function renderCoordinates(location){if(!location){coordinates.textContent='No verified location selected';coordinates.classList.add('pending');return}coordinates.textContent=`✓ Verified coordinates: ${location.lat.toFixed(6)}, ${location.lon.toFixed(6)}`;coordinates.classList.remove('pending')}
document.querySelectorAll('.edit-client').forEach(button=>button.addEventListener('click',()=>{const item=clientLocationData[+button.dataset.index];document.querySelector('.edit-modal').classList.add('client-edit');document.querySelector('#hourlyRate').value=item.rate;document.querySelector('#gstRate').value=item.gst;addressInput.value=item.address;selectedLocation=item;results.innerHTML='';renderCoordinates(item)}));
document.querySelectorAll('.edit-team').forEach(button=>button.addEventListener('click',()=>{document.querySelector('.edit-modal').classList.remove('client-edit');results.innerHTML=''}));
addressInput.addEventListener('input',()=>{selectedLocation=null;renderCoordinates(null);const query=addressInput.value.trim();results.innerHTML='';clearTimeout(addressTimer);if(query.length<4)return;addressTimer=setTimeout(async()=>{try{const url=`https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&countrycodes=au&limit=5&q=${encodeURIComponent(query)}`;const response=await fetch(url,{headers:{Accept:'application/json'}});if(!response.ok)throw new Error('Address service unavailable');const locations=await response.json();results.innerHTML=locations.length?locations.map((location,index)=>`<button type="button" class="address-result" data-index="${index}">${location.display_name}</button>`).join(''):'<div class="address-result">No Australian address found. Try adding suburb or postcode.</div>';results.querySelectorAll('.address-result[data-index]').forEach(button=>button.addEventListener('click',()=>{const location=locations[+button.dataset.index];selectedLocation={address:location.display_name,lat:+location.lat,lon:+location.lon};addressInput.value=selectedLocation.address;results.innerHTML='';renderCoordinates(selectedLocation)}))}catch(error){results.innerHTML='<div class="address-result">Address search is unavailable. Please try again.</div>'}},900)});
document.querySelector('.edit-modal').addEventListener('submit',()=>{if(editTarget?.kind!=='client')return;const index=editTarget.index;clientLocationData[index]={rate:+document.querySelector('#hourlyRate').value||0,gst:+document.querySelector('#gstRate').value,address:addressInput.value,lat:selectedLocation?.lat??null,lon:selectedLocation?.lon??null};clientRates[index]=clientLocationData[index].rate;const rateCell=document.querySelector(`#clientsTable .edit-client[data-index="${index}"]`).closest('tr').querySelector('.client-rate');rateCell.innerHTML=`$${clientLocationData[index].rate.toFixed(2)}<small>per hour</small>`;});
