const deleteOverlay=document.createElement('div');deleteOverlay.className='modal-backdrop';deleteOverlay.id='deleteModal';document.body.append(deleteOverlay);
let pendingDelete=null;
function deleteButton(type,label){return `<button class="delete-button" data-delete-type="${type}" data-delete-label="${label}">Delete</button>`}
document.querySelectorAll('#jobsTable tr').forEach((row,index)=>{const action=row.lastElementChild;action.insertAdjacentHTML('beforeend',deleteButton('job',row.querySelector('strong').textContent));action.style.whiteSpace='nowrap'});
document.querySelectorAll('#clientsTable tr').forEach(row=>row.lastElementChild.insertAdjacentHTML('beforeend',deleteButton('client',row.querySelector('strong').textContent)));
document.querySelectorAll('.team-card').forEach(card=>card.insertAdjacentHTML('beforeend',deleteButton('cleaner',card.querySelector('h3').textContent)));
document.querySelectorAll('#invoicesTable tr').forEach(row=>row.lastElementChild.insertAdjacentHTML('beforeend',deleteButton('invoice',row.querySelector('strong').textContent)));
function openDelete(button){const type=button.dataset.deleteType,label=button.dataset.deleteLabel;pendingDelete={button,type,label};deleteOverlay.innerHTML=`<section class="job-modal delete-modal"><button class="close-delete close-modal" type="button">×</button><div class="warning-icon">!</div><p class="eyebrow">DELETE ${type.toUpperCase()}</p><h2>Delete ${label}?</h2><p>This will remove the ${type} from the system. This action cannot be undone in this demo.</p><div class="delete-actions"><button class="invoice-button" id="cancelDelete">Cancel</button><button class="confirm-delete" id="confirmDelete">Delete ${type}</button></div></section>`;deleteOverlay.classList.add('open');deleteOverlay.querySelector('.close-delete').onclick=closeDelete;deleteOverlay.querySelector('#cancelDelete').onclick=closeDelete;deleteOverlay.querySelector('#confirmDelete').onclick=confirmDelete}
function closeDelete(){deleteOverlay.classList.remove('open');pendingDelete=null}
function confirmDelete(){const {button,type,label}=pendingDelete;const container=button.closest(type==='cleaner'?'.team-card':'tr');container.remove();closeDelete();document.querySelector('#toastText').textContent=`${label} was removed.`;toast.querySelector('strong').textContent=`${type[0].toUpperCase()+type.slice(1)} deleted`;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3600)}
document.querySelectorAll('[data-delete-type]').forEach(button=>button.addEventListener('click',()=>openDelete(button)));deleteOverlay.addEventListener('click',event=>{if(event.target===deleteOverlay)closeDelete()});
