(() => {
  'use strict';
  const key='cleanly-management-v1', $=s=>document.querySelector(s);
  const empty=()=>({vehicles:[],maintenance:[],transactions:[],employees:[],shifts:[],timesheets:[]});
  let data=empty(), storageError=false;
  try {const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved)for(const k of Object.keys(data)){if(!Array.isArray(saved[k]))throw Error('Invalid data');data[k]=saved[k];}}catch{storageError=true;}
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=v=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(v);
  const date=v=>v?new Date(v+'T12:00:00').toLocaleDateString('en-AU'):'—';
  const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Australia/Sydney'});
  const defs={
    vehicles:{title:'Fleet',icon:'▱',desc:'Vehicles, registration and operational readiness.',fields:[['name','Vehicle name'],['plate','Registration plate'],['state','State / territory','select','NSW,VIC,QLD,WA,SA,TAS,ACT,NT'],['odometer','Odometer (km)','number'],['rego','Registration expiry','date'],['status','Status','select','Active,Maintenance,Unavailable']]},
    maintenance:{title:'Maintenance',icon:'⚒',desc:'Plan servicing and track vehicle maintenance costs.',fields:[['vehicle','Vehicle','vehicles'],['name','Service / work order'],['due','Due date','date'],['cost','Estimated cost (AUD)','number'],['status','Status','select','Scheduled,In progress,Completed']]},
    transactions:{title:'Finance',icon:'↗',desc:'Income, expenses and GST estimates in Australian dollars.',fields:[['name','Description / reference'],['contact','Customer / supplier'],['type','Type','select','Income,Expense'],['amount','Amount excluding GST (AUD)','number'],['tax','GST treatment','select','10% GST,GST-free'],['date','Transaction date','date'],['due','Due date','date'],['status','Status','select','Unpaid,Paid']]},
    employees:{title:'People',icon:'♧',desc:'Your team directory and employment details.',fields:[['name','Full name'],['email','Email','email'],['role','Role'],['employment','Employment type','select','Full-time,Part-time,Casual,Contractor'],['rate','Base hourly rate (AUD)','number'],['status','Status','select','Active,On leave,Inactive']]},
    shifts:{title:'Roster',icon:'▦',desc:'Assign team members to sites and prevent overlapping shifts. Sydney local time.',fields:[['employee','Team member','employees'],['name','Site / assignment'],['date','Date','date'],['start','Start time','time'],['end','End time','time'],['status','Status','select','Draft,Published,Completed']]},
    timesheets:{title:'Timesheets',icon:'◷',desc:'Record and approve worked hours. Base pay estimates exclude awards, overtime and super.',fields:[['employee','Team member','employees'],['date','Date','date'],['start','Clock in','time'],['end','Clock out','time'],['break','Unpaid break (minutes)','number'],['status','Status','select','Pending,Approved']]}
  };
  let view='overview', query='', filter='All', editing=null;
  const label=(kind,id)=>data[kind].find(r=>r.id===id)?.name||'Unknown record';
  const hours=r=>{const mins=t=>Number(t.split(':')[0])*60+Number(t.split(':')[1]);return (mins(r.end)-mins(r.start)-Number(r.break||0))/60;};
  const total=r=>Math.round(Number(r.amount)*(r.tax==='10% GST'?1.1:1)*100)/100;
  const sum=(rows,fn)=>rows.reduce((s,r)=>s+fn(r),0);
  const metric=(name,value,note)=>`<article class="metric"><label>${name}</label><strong>${value}</strong><small>${note}</small></article>`;
  function toast(text){$('#message').textContent=text;$('#message').style.display='block';setTimeout(()=>$('#message').style.display='none',3500);}
  function commit(next){if(storageError){toast('Stored data could not be read. Export and recover your browser data before saving.');return false;}try{localStorage.setItem(key,JSON.stringify(next));data=next;return true;}catch{toast('Unable to save. Browser storage may be full or disabled.');return false;}}
  function metrics(){const tx=data.transactions, paid=tx.filter(r=>r.status==='Paid');return '<div class="metrics">'+metric('ACTIVE VEHICLES',data.vehicles.filter(r=>r.status==='Active').length,`${data.vehicles.length} vehicles in your fleet`)+metric('CASH MOVEMENT',money(sum(paid,r=>(r.type==='Income'?1:-1)*total(r))),'All recorded paid transactions')+metric('OUTSTANDING INCOME',money(sum(tx.filter(r=>r.type==='Income'&&r.status==='Unpaid'),total)),'Includes applicable GST')+metric('ACTIVE TEAM',data.employees.filter(r=>r.status==='Active').length,`${data.shifts.filter(r=>r.status==='Published').length} published shifts` )+'</div>';}
  function overview(){const due=data.maintenance.filter(r=>r.status!=='Completed'), exp=data.vehicles.filter(r=>r.rego<=today());return metrics()+`<div class="module-grid">${['vehicles','transactions','employees'].map(k=>`<a class="panel module" href="#${k}"><span class="symbol">${defs[k].icon}</span><b>${defs[k].title} management ↗</b><p>${defs[k].desc}</p><small>${data[k].length} records in your workspace</small></a>`).join('')}</div><div class="grid"><section class="panel"><h2>Needs your attention</h2><p>Upcoming work and registration reminders</p>${due.map(r=>`<div class="line"><span>${esc(r.name)}<br><small>${esc(label('vehicles',r.vehicle))}</small></span><b>${date(r.due)}</b></div>`).join('')}${exp.map(r=>`<div class="line"><span>${esc(r.name)}</span><span class="badge">Registration expired / due today</span></div>`).join('')}${!due.length&&!exp.length?'<div class="empty">All clear. Add vehicles and service dates to track reminders.</div>':''}</section><section class="panel"><h2>Workforce activity</h2><p>All recorded timesheets</p><div class="line"><span>Approved hours</span><b>${sum(data.timesheets.filter(r=>r.status==='Approved'),hours).toFixed(1)} h</b></div><div class="line"><span>Awaiting approval</span><b>${data.timesheets.filter(r=>r.status==='Pending').length}</b></div><div class="line"><span>Scheduled services</span><b>${due.length}</b></div><p>Your workspace starts empty. Add your own business records to get started.</p></section></div>`;}
  function cell(r,f){const [k,,type]=f;const v=r[k];if(type==='vehicles'||type==='employees')return esc(label(type,v));if(type==='date')return date(v);if(['amount','cost','rate'].includes(k))return money(Number(v));if(k==='status')return `<span class="badge">${esc(v)}</span>`;return esc(v);}
  function financeSummary(){const rows=data.transactions, paid=rows.filter(r=>r.status==='Paid');const gst=r=>Math.round(Number(r.amount)*.1*100)/100;return `<div class="metrics">${metric('PAID INCOME',money(sum(paid.filter(r=>r.type==='Income'),total)),'GST inclusive')}${metric('PAID EXPENSES',money(sum(paid.filter(r=>r.type==='Expense'),total)),'GST inclusive')}${metric('NET GST ESTIMATE',money(sum(paid.filter(r=>r.tax==='10% GST'),r=>(r.type==='Income'?1:-1)*gst(r))),'Paid records only · not a BAS return')}${metric('OVERDUE ITEMS',rows.filter(r=>r.status==='Unpaid'&&r.due<today()).length,'Unpaid and past due date')}</div>`;}
  function table(){const def=defs[view];const rows=data[view].filter(r=>(filter==='All'||r.status===filter)&&def.fields.some(f=>String(f[2]==='vehicles'||f[2]==='employees'?label(f[2],r[f[0]]):r[f[0]]).toLowerCase().includes(query.toLowerCase())));$('#rows').innerHTML=rows.length?rows.map(r=>`<tr>${def.fields.map(f=>`<td>${cell(r,f)}</td>`).join('')}${view==='transactions'?`<td>${money(total(r))}</td>`:''}${view==='timesheets'?`<td>${hours(r).toFixed(2)}</td>`:''}<td><button class="secondary" data-edit="${esc(r.id)}">Edit</button></td></tr>`).join(''):`<tr><td colspan="12" class="empty">${data[view].length?'No matching records.':'No records yet. Add your first record to get started.'}</td></tr>`;}
  function render(){const def=defs[view];$('#navigation').innerHTML=`<a href="#overview" class="${view==='overview'?'active':''}"><span>◈</span>Overview</a>`+Object.entries(defs).map(([k,d])=>`<a href="#${k}" class="${view===k?'active':''}"><span>${d.icon}</span>${d.title}</a>`).join('');$('#title').textContent=def?def.title:'Business overview';$('#breadcrumb').textContent=def?def.title:'Overview';$('#subtitle').textContent=def?def.desc:'A clearer view of your fleet, finances and people.';$('#create').textContent=view==='overview'?'+ Add vehicle':'+ Add record';if(!def){$('#content').innerHTML=overview();return;}$('#content').innerHTML=(view==='transactions'?financeSummary():'')+`<section class="panel"><div class="toolbar"><input id="search" placeholder="Search ${def.title.toLowerCase()}…" aria-label="Search records"><select id="filter" aria-label="Filter by status"><option>All</option>${def.fields.find(f=>f[0]==='status')[3].split(',').map(s=>`<option>${s}</option>`).join('')}</select><button id="export" class="secondary">Export CSV ↓</button></div><div class="table-scroll"><table><thead><tr>${def.fields.map(f=>`<th>${f[1]}</th>`).join('')}${view==='transactions'?'<th>Total incl. GST</th>':''}${view==='timesheets'?'<th>Hours</th>':''}<th>Action</th></tr></thead><tbody id="rows"></tbody></table></div></section>`;$('#search').value=query;$('#filter').value=filter;$('#search').oninput=e=>{query=e.target.value;table();};$('#filter').onchange=e=>{filter=e.target.value;table();};$('#export').onclick=exportCSV;table();}
  function openForm(id){if(view==='overview'){location.hash='vehicles';view='vehicles';render();}editing=id||null;const r=data[view].find(x=>x.id===id)||{}, def=defs[view];$('#formTitle').textContent=(id?'Edit ':'Add ')+def.title.toLowerCase()+' record';$('#error').textContent='';$('#fields').innerHTML=def.fields.map(([k,l,t='text',opts])=>{let input;if(t==='select'||t==='vehicles'||t==='employees'){const options=t==='select'?opts.split(',').map(v=>[v,v]):data[t].map(v=>[v.id,v.name]);input=`<select name="${k}" required>${t!=='select'?'<option value="">Select a record</option>':''}${options.map(([v,text])=>`<option value="${esc(v)}" ${String(r[k])===v?'selected':''}>${esc(text)}</option>`).join('')}</select>`;}else input=`<input name="${k}" type="${t}" required ${t==='number'?'min="0" step="0.01"':''} maxlength="160" value="${esc(r[k]??(t==='date'?today():''))}">`;return `<label>${l}${input}</label>`;}).join('');$('#editor').showModal();}
  $('#recordForm').onsubmit=e=>{e.preventDefault();const r=Object.fromEntries(new FormData(e.target));for(const k in r)r[k]=r[k].trim();if(Object.values(r).some(v=>!v))return $('#error').textContent='Complete all fields.';for(const [k,,type] of defs[view].fields){if(type==='number'&&(!Number.isFinite(Number(r[k]))||Number(r[k])<0))return $('#error').textContent='Enter valid non-negative numbers.';}if(view==='vehicles'){r.plate=r.plate.toUpperCase();if(data.vehicles.some(x=>x.id!==editing&&x.plate===r.plate&&x.state===r.state))return $('#error').textContent='This registration already exists.';}if(view==='shifts'||view==='timesheets'){if(r.end<=r.start)return $('#error').textContent='End time must follow start time. Split overnight work into two dates.';if(view==='timesheets'&&hours(r)<=0)return $('#error').textContent='Break must be shorter than the worked period.';if(view==='shifts'&&data.shifts.some(x=>x.id!==editing&&x.employee===r.employee&&x.date===r.date&&r.start<x.end&&r.end>x.start))return $('#error').textContent='This employee already has an overlapping shift.';}r.id=editing||crypto.randomUUID();const next={...data,[view]:editing?data[view].map(x=>x.id===editing?r:x):[...data[view],r]};if(commit(next)){$('#editor').close();render();toast('Record saved in this browser.');}};
  function exportCSV(){const fields=defs[view].fields;const safe=v=>'"'+String(v??'').replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"';const lines=[fields.map(f=>f[1]),...data[view].map(r=>fields.map(f=>['vehicles','employees'].includes(f[2])?label(f[2],r[f[0]]):r[f[0]]))];const url=URL.createObjectURL(new Blob(['\uFEFF'+lines.map(row=>row.map(safe).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`ois-${view}-${today()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  $('#create').onclick=()=>openForm();$('#close').onclick=$('#cancel').onclick=()=>$('#editor').close();$('#content').onclick=e=>{const b=e.target.closest('[data-edit]');if(b)openForm(b.dataset.edit);};function route(){const hash=location.hash.slice(1);view=defs[hash]?hash:'overview';query='';filter='All';render();}window.addEventListener('hashchange',route);route();if(storageError)toast('Saved data could not be read. Saving is disabled to preserve it.');
})();
