const http=require('http');
const fs=require('fs');
const path=require('path');
const root=__dirname;
function loadEnv(){const envPath=path.join(root,'.env');if(!fs.existsSync(envPath))return;fs.readFileSync(envPath,'utf8').split(/\r?\n/).forEach(line=>{const match=line.match(/^([^#=\s]+)\s*=\s*(.*)$/);if(match&&!process.env[match[1]])process.env[match[1]]=match[2].replace(/^["']|["']$/g,'')})}
loadEnv();
const telegramToken=process.env.TELEGRAM_BOT_TOKEN;
const jobs=new Map();
function json(res,status,body){res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify(body))}
function body(req){return new Promise((resolve,reject)=>{let raw='';req.on('data',chunk=>{raw+=chunk;if(raw.length>1e6)reject(new Error('Request too large'))});req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{})}catch{reject(new Error('Invalid JSON'))}});req.on('error',reject)})}
async function telegram(method,payload){if(!telegramToken)throw new Error('TELEGRAM_BOT_TOKEN is not configured');const response=await fetch('https://api.telegram.org/bot'+telegramToken+'/'+method,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!data.ok)throw new Error(data.description||'Telegram request failed');return data.result}
function jobMessage(job){return '🧹 *NEW JOB*\n\n*Client:* '+job.client+'\n📍 *Address:* '+job.address+'\n📅 *Date:* '+job.date+'\n🕘 *Time:* '+job.time+'\n⏱️ *Duration:* '+job.duration+' hours\n\nPlease confirm your availability below.'}
async function routeApi(req,res,url){if(req.method==='GET'&&url.pathname==='/api/health')return json(res,200,{ok:true,telegramConfigured:Boolean(telegramToken)});if(req.method==='POST'&&url.pathname==='/api/telegram/send-job'){try{const job=await body(req);if(!job.chatId||!job.client||!job.date||!job.time)return json(res,400,{ok:false,error:'chatId, client, date and time are required'});const jobId=crypto.randomUUID();jobs.set(jobId,{...job,status:'sent'});await telegram('sendMessage',{chat_id:job.chatId,text:jobMessage(job),parse_mode:'Markdown',reply_markup:{inline_keyboard:[[{text:'✅ Confirm job',callback_data:'job:'+jobId+':confirm'},{text:'❌ I cannot attend',callback_data:'job:'+jobId+':decline'}]]}});return json(res,200,{ok:true,jobId})}catch(error){return json(res,502,{ok:false,error:error.message})}}if(req.method==='POST'&&url.pathname==='/api/telegram/webhook'){try{const update=await body(req);const callback=update.callback_query;if(callback&&callback.data&&callback.data.startsWith('job:')){const [,jobId,decision]=callback.data.split(':');const job=jobs.get(jobId);if(job){job.status=decision==='confirm'?'confirmed':'declined';await telegram('answerCallbackQuery',{callback_query_id:callback.id,text:decision==='confirm'?'Job confirmed':'Manager will be notified'});await telegram('editMessageReplyMarkup',{chat_id:callback.message.chat.id,message_id:callback.message.message_id,reply_markup:{inline_keyboard:[]}})}return json(res,200,{ok:true})}return json(res,200,{ok:true})}catch(error){return json(res,502,{ok:false,error:error.message})}}return false}
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json'};
http.createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost');if(url.pathname.startsWith('/api/')){const handled=await routeApi(req,res,url);if(handled!==false)return}const safePath=url.pathname==='/'?'/index.html':url.pathname;const filePath=path.resolve(root,'.'+safePath);if(!filePath.startsWith(root+path.sep)){res.writeHead(403);return res.end('Forbidden')}fs.readFile(filePath,(error,data)=>{if(error){res.writeHead(error.code==='ENOENT'?404:500);return res.end('Not found')}res.writeHead(200,{'Content-Type':mime[path.extname(filePath)]||'application/octet-stream'});res.end(data)})}).listen(process.env.PORT||3000,()=>console.log('Cleanly running on http://localhost:'+(process.env.PORT||3000)));
